global using Microsoft.AspNetCore.Components.Rendering;
global using Microsoft.AspNetCore.Components;
global using MudBlazor;
global using Paymentsystem.Shared.Models;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using Paymentsystem.Shared.ViewModels;